### ISSUE TITLE
Change share icons to Font Awesome 5

### ISSUE THREAD

**Issue by tnke** [evermade/swiss#4]
Page sharing icons classes need to be changed from `fa` to `fab` to support Font Awesome 5. Only applies to the social media platform icons, email icon should be left as it is.

**Comment by onefastsnail** [comment]
Sweet!

Could we also create a demo component in the toolbox? And uncomment its usage in the single template? Just so out the box it's visible. 

There's a `c-social-media-ul` which could be refactored and rename to `c-social-media`.
